### ISSUE TITLE
vagrantbox search shows wrong version for leap15.5

### ISSUE THREAD

**Issue by peterdd** [openSUSE/vagrant#48]
(Didn't know if it is the appropriate place to report, but it is easiest way for me)

https://app.vagrantup.com/opensuse/boxes/Leap-15.5.x86_64 
(and aarch too)

has listed version v15.5.10.94

But when I do a vagrant box update for instance

```
vagrant box update
==> default: Checking for updates to 'opensuse/Leap-15.5.x86_64'
    default: Latest installed version: 15.5.10.117
    default: Version constraints: 
    default: Provider: virtualbox
==> default: Box 'opensuse/Leap-15.5.x86_64' (v15.5.10.117) is running the latest version.
```

This issue exists since a few weeks (I had 15.5.10.94 before and it updated to 15.5.10.117, I thought it would eventually heal/'cache refresh' on app.vagrantup.com website. Or is there something fishy?

**Comment by dcermak** [comment]
This is a bug in hashicorps vagrantcloud webui, it does not sort versions properly. If you scroll down, you'll find version 15.5.10.117 at the bottom:
![image](https://github.com/openSUSE/vagrant/assets/45594031/2ff94ec2-26fa-4bc8-94cd-9d951abfab87)

(because clearly 117 < 57 :zany_face:)

Sadly this is nothing that we can fix. You can try to report this upstream, maybe it will get resolved.
